title: "{{ callysto_html_hostname }}"
domain: "{{ callysto_html_domain }}"
email: "{{ callysto_html_support_email }}"
url: "{{ callysto_html_url }}"
longname: "{{ callysto_html_longname }}"
terms: "{{ callysto_html_terms }}"

relative_permalinks: false

exclude: [CNAME, README.md, LICENSE, ansible.sh]
